// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmfAbYLCTXgLz8Hl0A07ognjAXuvyXyb8',
    appId: '1:1065897214692:web:a68a2d3de3c331de2ea2f1',
    messagingSenderId: '1065897214692',
    projectId: 'bee-alive',
    authDomain: 'bee-alive.firebaseapp.com',
    databaseURL: 'https://bee-alive-default-rtdb.firebaseio.com',
    storageBucket: 'bee-alive.firebasestorage.app',
    measurementId: 'G-MEE9XYJT6B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4rv82bqLAAoMHsB8NteIRqWMAjEYJDLo',
    appId: '1:1065897214692:android:b627af7d899325272ea2f1',
    messagingSenderId: '1065897214692',
    projectId: 'bee-alive',
    databaseURL: 'https://bee-alive-default-rtdb.firebaseio.com',
    storageBucket: 'bee-alive.firebasestorage.app',
  );

}